### ISSUE TITLE
Impossible to install over ssh

### ISSUE THREAD

**Issue by wasowski** [IagoAbal/eba#1]
It seems that one needs to use https to access the github repo not ssh (which is suggested in the INSTALL.md).    HTTPs works without any permissions (for open projects).

Incidentally, it might also be helpful to suggest checking out a concrete tag, instead of HEAD, which might be a volatile target long term. But I suppose that this will be fixed naturally when you actually release.

**Comment by IagoAbal** [comment]
Thanks for pointing it out, and sorry for taking almost a year to reply and fix it! Hopefully I'm faster next time.
